---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    istio-injection: enabled
    #istio.io/dataplane-mode: ambient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: simple-color-app
        image: robarros/simple-color-app:1.0.0
        env:
          - name: APP_COLOR
            value: green
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo
  namespace: app
spec:
  selector:
    app: app-demo
  ports:
    - name: http
      port: 80
      targetPort: 3000

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: app-gateway
  namespace: app
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - app-demo.virtualti.net
    - port:
        number: 443
        name: https
        protocol: HTTP
      hosts:
        - app-demo.virtualti.net
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-demo
  namespace: app
spec:
  hosts:
    - app-demo.virtualti.net
  gateways:
    - app-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app-demo.app.svc.cluster.local
            port:
              number: 80
