apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: meu-app-rollout
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: meu-app-rollout
  
  minReplicaCount: 10
  maxReplicaCount: 20

  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
