---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: meu-app-rollout
  namespace: app
spec:
  #replicas: 10
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
      - name: simple-color-app
        image: robarros/simple-color-app:1.0.0
        env:
          - name: APP_COLOR
            value: green
          - name: ERROR_RATE
            value: '0'
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
  strategy:
    canary:
      canaryService: app-canary
      stableService: app-stable
      trafficRouting:
        istio:
          virtualService:
            name: app-vs
            routes:
            - primary-route
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 80
      - pause: {}
