---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: meu-app-rollout
  namespace: app
  # tags.datadoghq.com/env: "dev"
  # tags.datadoghq.com/service: "meu-app"
  # tags.datadoghq.com/version: "1.4.0"
spec:
  #replicas: 10
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
        # tags.datadoghq.com/env: "dev"
        # tags.datadoghq.com/service: "meu-app"
        # tags.datadoghq.com/version: "1.4.0"
        # admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/config.mode: "socket"
        admission.datadoghq.com/inject-traces: "true"
    spec:
      containers:
      - name: simple-color-app
        image: robarros/simple-color-app:1.0.0
        env:
          - name: APP_COLOR
            value: purple
          - name: ERROR_RATE
            value: '0'
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION 
            valueFrom: 
              fieldRef: 
                fieldPath: metadata.labels['tags.datadoghq.com/version']
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 100Mi
  strategy:
    canary:
      canaryService: app-canary
      stableService: app-stable
      trafficRouting:
        istio:
          virtualService:
            name: app-vs
            routes:
            - primary-route
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 80
      - pause: {}
